export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const SET_EDUCATIONAL_DETAILS = "SET_EDUCATIONAL_DETAILS";
export const GET_UNIVERSITIES_DETAILS_START = "GET_UNIVERSITIES_DETAILS_START";
export const GET_UNIVERSITIES_DETAILS_SUCCESS = "GET_UNIVERSITIES_DETAILS_SUCCESS";
export const GET_UNIVERSITIES_DETAILS_FAILURE = "GET_UNIVERSITIES_DETAILS_FAILURE";
